[project]
name = "my-chatgpt"
version = "0.1.0"
description = "API FastAPI para enviar mensagens ao GPT-4o"
authors = [
    { name = "Carlos Arruda", email = "caugustogarruda@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
